
version: "3.8"
services:
  pyshot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PATH=/root/.local/bin:$PATH
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "pyshot.screenshot_router:app",
        "--reload",
      ]